services:
  postgres:
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: todo
      PGDATA: /data/postgres
    volumes:
      - ./pg-data-only:/data/postgres
    ports:
      - "5432:5432"